fragment ExerciseLog on ExerciseLog {
    id
    exercise {
        ...Exercise
    }
    logDateTime
    repetitions
    logValue {
        ...LogValue
    }
    warmup
    remark
}

fragment ExerciseLineChartData on ExerciseLineChartData {
    monthLabel
    logs {
        ...ExerciseLog
    }
}
