fragment ExerciseLog on ExerciseLog {
    id
    exercise {
        ...Exercise
    }
    logDateTime
    repetitions
    weightValueLeft {
        ...WeightValue
    }
    weightValueRight {
        ...WeightValue
    }
    warmup
    remark
}