fragment ProgramShort on Program {
    id
    name
    createdDateTime
    active
    remark
}

fragment ProgramLong on Program {
    id
    name
    createdDateTime
    active
    remark
    logGroups {
        ...ProgramLogGroup
    }
}
