fragment ProgramShort on Program {
    id
    name
    createdDateTime
    active
    remark
}

fragment ProgramLong on Program {
    id
    name
    createdDateTime
    active
    remark
    logGroups {
        ...ProgramLogGroup
    }
}

fragment ScheduledProgram on ScheduledProgram {
    id
    program {
        ...ProgramShort
    }
    workout {
        ...WorkoutShort
    }
    scheduledDateTime
    remark
}
