fragment ProgramLog on ProgramLog {
    id
    programLogGroup {
        id
    }
    effort
    exercise {
        ...Exercise
    }
    logValue {
        ...LogValue
    }
    repetitions
    subdivisions {
        programLogGroup {
            id
        }
        repetitions
        logValue {
            ...LogValue
        }
        effort
        exercise {
            ...Exercise
        }
        intervalSeconds
        cooldownSeconds
        exerciseLog {
            ...ExerciseLog
        }
    }
    intervalSeconds
    cooldownSeconds
    exerciseLog {
        ...ExerciseLog
    }
}
