fragment ProgramShort on Program {
    id
    name
    createdDateTime
    active
    remark
}

fragment ProgramLong on Program {
    id
    name
    createdDateTime
    active
    remark
    logGroups {
        ...ProgramLogGroup
    }
}

fragment ProgramWorkoutLog on ProgramWorkoutLog {
    id
    programLog {
        ...ProgramLog
    }
}

fragment ProgramWorkoutGroup on ProgramWorkoutGroup {
    id
    type
    programWorkoutLogs {
        ...ProgramWorkoutLog
    }
}

fragment ProgramWorkout on ProgramWorkout {
    id
    #    program {
    #        ...ProgramLong
    #    }
    workout {
        ...WorkoutShort
    }
    groups {
        ...ProgramWorkoutGroup
    }
}

fragment ProgramWorkoutLong on ProgramWorkout {
    id
    workout {
        ...WorkoutLong
    }
    groups {
        ...ProgramWorkoutGroup
    }
}

fragment ScheduledProgram on ScheduledProgram {
    id
    programWorkout {
        ...ProgramWorkout
    }
    scheduledDateTime
}

fragment ScheduledProgramLong on ScheduledProgram {
    id
    programWorkout {
        ...ProgramWorkoutLong
    }
    scheduledDateTime
}
