fragment WorkoutShort on Workout {
    id
    name
    muscleGroups
    startDateTime
    endDateTime
    active
    remark
    estimatedCaloriesBurned
    status
}

fragment WorkoutLong on Workout {
    id
    name
    muscleGroups
    startDateTime
    endDateTime
    active
    groupedExerciseLogs {
        ...GroupedExerciseLog
    }
    remark
    externalHealthProviderData {
        appleHealthId
        provider
    }
}


fragment MuscleGroupChartData on MuscleGroupChartData {
    color
    muscleGroup
    count
}
