query workouts {
    myWorkouts {
        ...WorkoutShort
    }
}

query workoutsAndScheduledWorkouts {
    myWorkouts {
        ...WorkoutShort
    }
    myScheduledPrograms {
        ...ScheduledProgram
    }
}
