query myScheduledProgram {
    myScheduledPrograms {
        ...ScheduledProgram
    }
}

query scheduledProgramById($id: ID!) {
    scheduledProgramById(id: $id) {
        ...ScheduledProgram
    }
}
